### ISSUE TITLE
Creating VMs via --template fails

### ISSUE THREAD

**Issue by abonillabeeche** [belgaied2/harvester-cli#13] opened 2022-06-01 15:38 UTC
% harvester vm create --template small-ubuntu k3s --count 5
WARN[0000] You are using a template flag, please be aware that any other flag will be IGNORED! 
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/belgaied2/harvester-cli/cmd.vmCreateFromImage(0xc0005094a0, 0xc00043a870, 0xc0003de700)
	/github/workspace/cmd/vm.go:492 +0x7a5
github.com/belgaied2/harvester-cli/cmd.vmCreateFromTemplate(0xc0005094a0, 0xc00043a870)
	/github/workspace/cmd/vm.go:408 +0x925
github.com/belgaied2/harvester-cli/cmd.vmCreate(0xc0005094a0)
	/github/workspace/cmd/vm.go:314 +0x65
github.com/urfave/cli.HandleAction({0x22f0100?, 0x271c628?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x262f895, 0x6}, {0x0, 0x0}, {0xc00021b0b0, 0x1, 0x1}, {0x2635f05, 0xb}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00029ee00, 0xc000509080)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0x263afe7, 0xe}, {0x0, 0x0}, {0xc00021b070, 0x1, 0x1}, {0x265add9, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0x263afe7, 0xe}, {0x0, 0x0}, {0xc00021b070, 0x1, 0x1}, {0x265add9, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc00029e700, {0xc0003cf800, 0x8, 0x8})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.mainErr()
	/github/workspace/main.go:90 +0x191d
main.main()
	/github/workspace/main.go:19 +0x19

Furthermore, creating them without a template, runs fine.

(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm create k3s               
(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm list      
STATE         NAME                                  NODE      CPU       RAM       IP Address
Running       k3s                                             1         1Gi       
Not Running   neuvector-rodeo-jeos-b997b6f6-5fcvw   r620-2    2         5461Mi    10.0.0.196
Not Running   neuvector-rodeo-jeos-b997b6f6-vr24v   r620-1    2         5461Mi    10.0.0.66
Not Running   neuvector-rodeo-jeos-b997b6f6-zxdlv   r620-3    2         5461Mi    10.0.0.39
(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm create k3s --count 5
(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm list                
STATE         NAME                                  NODE      CPU       RAM       IP Address
Running       k3s                                   r620-2    1         1Gi       
Running       k3s-1                                           1         1Gi       
Running       k3s-2                                           1         1Gi       
Running       k3s-3                                           1         1Gi       
Running       k3s-4                                           1         1Gi       
Running       k3s-5                                           1         1Gi       
Not Running   neuvector-rodeo-jeos-b997b6f6-5fcvw   r620-2    2         5461Mi    10.0.0.196
Not Running   neuvector-rodeo-jeos-b997b6f6-vr24v   r620-1    2         5461Mi    10.0.0.66
Not Running   neuvector-rodeo-jeos-b997b6f6-zxdlv   r620-3    2         5461Mi    10.0.0.39

**Comment by belgaied2** [comment] 2022-06-28 09:01
Unfortunately, I was not able to reproduce the issue. Also, in the code, I don't see how the map at that position can be nil.

**Comment by abonillabeeche** [comment] 2022-07-14 20:30
What can I provide?

(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm create --template small-ubuntu wal --count 3 
WARN[0000] You are using a template flag, please be aware that any other flag will be IGNORED! 
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/belgaied2/harvester-cli/cmd.vmCreateFromImage(0xc0003e38c0, 0xc000284c30, 0xc000338700)
	/github/workspace/cmd/vm.go:480 +0x7a5
github.com/belgaied2/harvester-cli/cmd.vmCreateFromTemplate(0xc0003e38c0, 0xc000284c30)
	/github/workspace/cmd/vm.go:396 +0x925
github.com/belgaied2/harvester-cli/cmd.vmCreate(0xc0003e38c0)
	/github/workspace/cmd/vm.go:302 +0x65
github.com/urfave/cli.HandleAction({0x22f4940?, 0x2721eb0?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x26349cf, 0x6}, {0x0, 0x0}, {0xc0002470b0, 0x1, 0x1}, {0x263b076, 0xb}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0003b1500, 0xc0003e34a0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0x264015b, 0xe}, {0x0, 0x0}, {0xc000247070, 0x1, 0x1}, {0x2660130, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0x264015b, 0xe}, {0x0, 0x0}, {0xc000247070, 0x1, 0x1}, {0x2660130, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc0003b1340, {0xc00003b500, 0x8, 0x8})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.mainErr()
	/github/workspace/main.go:90 +0x16bd
main.main()
	/github/workspace/main.go:19 +0x19
(⎈ |local:default)abonilla@MacBookPro ~ % harvester vm create --template small-ubuntu wal          
WARN[0000] You are using a template flag, please be aware that any other flag will be IGNORED! 
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/belgaied2/harvester-cli/cmd.vmCreateFromImage(0xc0003738c0, 0xc00037f720, 0xc0000a2700)
	/github/workspace/cmd/vm.go:480 +0x7a5
github.com/belgaied2/harvester-cli/cmd.vmCreateFromTemplate(0xc0003738c0, 0xc00037f720)
	/github/workspace/cmd/vm.go:396 +0x925
github.com/belgaied2/harvester-cli/cmd.vmCreate(0xc0003738c0)
	/github/workspace/cmd/vm.go:302 +0x65
github.com/urfave/cli.HandleAction({0x22f4940?, 0x2721eb0?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x26349cf, 0x6}, {0x0, 0x0}, {0xc000218dc0, 0x1, 0x1}, {0x263b076, 0xb}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00052aa80, 0xc000373340)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0x264015b, 0xe}, {0x0, 0x0}, {0xc000218d80, 0x1, 0x1}, {0x2660130, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0x264015b, 0xe}, {0x0, 0x0}, {0xc000218d80, 0x1, 0x1}, {0x2660130, 0x24}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc00052a8c0, {0xc000222780, 0x6, 0x8})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.mainErr()
	/github/workspace/main.go:90 +0x16bd
main.main()
	/github/workspace/main.go:19 +0x19

**Comment by belgaied2** [comment] 2022-07-15 12:21
Solved as of v0.1.2 and 926218df1595d7efdc9c879d723e278f72e58fe9 
Closing

**Closed as completed by belgaied2** 2022-07-15 12:21 UTC
